### ISSUE TITLE
REOPENED The server own is racist to people do not join, also edits and falsly closes posts

### ISSUE THREAD

**Issue by NathanFromRs** [kaliflowerx3/ZoltriTWserver#14]
Just thought you might want to see that Kali is the server owner and hates all white people. Also a sjw. Banned me because i thought it was ridiculous, and that my discord was hacked ( which i find its more of a blessing because she is just crazy at this point) the server has changed after 2 years.

![Screenshot_20190426-165746](https://user-images.githubusercontent.com/50037535/57004023-28315200-6b99-11e9-809e-9ea09372c371.png)

also if any GItHub Administrators see this, please note: she is very good at editing/manipulating and i have more screenshots like this.

Do note she is trying to use photoshop in a message I didn't send below claiming I deleted it.

Also do note she is faking to be me and deleting/closing my post. I am warning you do not join this server.

**Comment by NathanFromRs** [comment]
Also Kali if you think Im going to simply leave, you are wrong. I am watching the posts closely. Do not edit my posts in photoshop or any editor. Pretending to be me. Also if any github mod wants to speak to me please do so as I already am in process of talking to one Kali. I will be showing said mod your little edit.

**Comment by BurningBodies** [comment]
Wow we really doing this again huh? She was trying to show him an example that not all feminists are bad because Nathan here said they're all horrible she was proving a point that one person doesnt make everyone bad so we all posted proof of him messing with us and figured the case was closed cause its obvious he is lying 
![Screenshot_20190430-082801_Discord](https://user-images.githubusercontent.com/50141716/57006737-28d5e280-6bb1-11e9-90a6-afc53b880f0c.jpg)

**Comment by BurningBodies** [comment]
You also wrote this whole thing on the last post and as you can see with your own two eyes this is my email on my phone \o/
![Screenshot_20190501-013951_Email](https://user-images.githubusercontent.com/50141716/57006891-5a9b7900-6bb2-11e9-932e-cde65abe9e16.jpg)

**Comment by DerpDude** [comment]
Nathan, just give it up. You're not going to get it your way. I've known Kali for over a year. She would NEVER be racist. Hell, she's the last person that would be racist. She was proving a damn point. Now drop it.

**Comment by DerpDude** [comment]
Besides. This is a place to post server issues. Not your own.

**Comment by Asmodeuss666** [comment]
I wonder how we could photoshop phone screenshots, I can record my whole screen and put a video link with the whole chat log so mods can have fun with it, and you know what, this is the moment you go down Nathan, you narcissist hypocrit guy, you're just mad you got banned, you had a base, you put time in it, I understand you're pissed but hey, don't be an asshole like you were, and most importantly do not try to bring the server down with you, because we are a few to have proof you are lying everytime we see you typing, except when you're threatening kali, now here is 6 SCREENSHOTS that will bring YOU down instead of the server, good luck fighting back with the tea I'm about to put here:

THE FIRST 3 SCREENS YOU KNOW THEM ALREADY:

![Screenshot_20190426-235615](https://user-images.githubusercontent.com/50142636/57011343-83972a80-6c01-11e9-9396-f8734d2dbef6.jpg)
![Screenshot_20190426-235857](https://user-images.githubusercontent.com/50142636/57011344-83972a80-6c01-11e9-999d-b24c53acc603.jpg)
![Screenshot_20190430-150249__01](https://user-images.githubusercontent.com/50142636/57011345-83972a80-6c01-11e9-8bf0-128c520a6009.jpg)

Then here is the one where you tell me how proud you are because you left a permanent scar, but hey, we're over this okay, you're just not, I think you even have issues with yourself but it is okay, we know it, today's life is hard and you need attention.

![Screenshot_20190501-102606](https://user-images.githubusercontent.com/50142636/57011347-842fc100-6c01-11e9-87d5-95083a6a3b2b.jpg)

On the one bellow you tell me you're trying to bring every single "posts" of the server down on any platform, and here we are, still, fighting back cause: WE. DON'T. OWE. YOU.

![Screenshot_20190501-102709](https://user-images.githubusercontent.com/50142636/57011348-842fc100-6c01-11e9-8233-ecfa96e6267c.jpg)

Finally this last one is the mail I received when you posted the comment you deleted, I bet you forgot every single person commenting the thread gets a mail when someone responds, no go on, tell everyone it is photoshop, but we all know the truth, you're just giving us more and more reasons to keep fighting, give up now, i'll keep the screens I have away (4 more waiting to show themselves, they really want to) or go on, tell one more time kali is racist and I'll take them out for a walk

![Screenshot_20190501-110210](https://user-images.githubusercontent.com/50142636/57011349-842fc100-6c01-11e9-9ff2-c140bce08885.jpg)



Truly yours Nathan, Truly yours <3

**Comment by NathanFromRs** [comment]
Manipulation from Kali and Photoshop.

**Comment by BurningBodies** [comment]
Wow you really dumb huh? You think someone who is not in college and cheated during high school can Photoshop? Wow you think highly of me thank you I guess you're very wrong though? And sadly three different pictures and several screenshots are too much work to Photoshop. It even shows our mails in different languages why would we have that if you can't understand it? Idiot just accept that you lost you cant use 'Photoshop' as an excuse every time. And news flash it is 6 am my time and Kali isn't awake so she cant manipulate me \o/

**Comment by DerpDude** [comment]
Are you serious? There's no way in hell that the mail could have been photoshopped. You have to be one of the most ridiculous people I have ever met. You can't even photoshop those discord convos. By this point you're just grasping at straws. Just leave us be.

**Comment by BurningBodies** [comment]
Honestly if I had Photoshop I would have to learn how to use it first before I could even do anything and this is a gaming laptop I don't think Photoshop is meant for it but I would rather make you say you are a cow nut flicker in those instead lul sadly we dont Photoshop you are just trying to come at us because your man ego got hurt by a girl

**Comment by kaliflowerx3** [comment]
Nathan you know that Github has logs of who posted what and then deleted it right?
